### ISSUE TITLE
QR code support - feature request

### ISSUE THREAD

**Issue by JannemanDev** [lgommans/dro.pm#12]
Hi,

I really like your website and I use it all the time in my class. Often I share a link on the big screen with them and it would be really cool and handy if they could also just scan a big QR code instead of typing in dro.pm/X (which they often misspell by the way:))

**Comment by lgommans** [comment]
Woa, has it been three weeks already? I've been meaning to get around to this, figuring it's not a lot of work so I'd just reply when it's done but... alas. It is on my radar, probably I will make a button next to the current "open link" button thingy (this one: ![external link icon](https://dro.pm/res/img/exturl.png)).

I originally didn't make this because the idea behind dropm is that the links are short enough to just type in a few characters. But this was back in 2010 or something when people didn't know how to use QR code readers the way that they do now that it's reliably built into their camera apps (I've recently come across the first person who was confused I used an 'advanced' QR code app!). If QR codes are the method of transfer, then one might as well have a long link that can be valid forever, defeating the purpose of dropm -- or so was my thinking back then. I realise now that it's not an either-or situation and that adding QR code support will be a nice addition also with short links. Thanks for voicing the wish, that's how I know what people would like :) even if I don't get around to it in a timely manner :(

**Comment by lgommans** [comment]
New year's present. Happy new leap year :D
