### ISSUE TITLE
File input not detecting changes...

### ISSUE THREAD

**Issue by ayunami2000** [lgommans/dro.pm#14]
When you upload a file and then delete it, the website does not clear the file input, so, if I was to, say, recompile my jar with some updated code, and then try uploading it, it does not detect the file change. The fix is to clear the file input after a file has been selected, so it can always detect a new file.

**Comment by lgommans** [comment]
Good suggestion! I actually noticed this myself a few days ago, though not sure where and now I can't actually reproduce it in a couple of browsers. But I can see the field is cleared when calling `form.reset()` so that fix hopefully works in whatever browser you/we ran into this bug :). Let me know if this doesn't adequately fix it!

**Comment by ayunami2000** [comment]
Indeed seems to be fixed, thank you!
