### ISSUE TITLE
Switching between short and custom link doesn't upload previously entered content

### ISSUE THREAD

**Issue by MagicLegend** [lgommans/dro.pm#4]
A picture says more than a thousand words:
![Gifje](https://i.imgur.com/2ypqln8.gif)

Issue is that the newly entered custom url is not valid until the textbox used for entering content is touched. Also shouldn't this action invalidate the old url (dro.pm/e in this example)? Otherwise you'd still end up with a copy of the content that could be easily found by others.

**Comment by lgommans** [comment]
Thanks for the report! Not sure when I'll have time to work on this, maybe this weekend (if nobody beats me to it) or maybe later.

**Comment by lgommans** [comment]
[master b112298] Fix #4
     4 files changed, 168 insertions(+), 51 deletions(-)

Well, that turned out to be a little more elaborate than expected. To fix this properly, I basically made two new API endpoints (`move` to move one link's contents to another when switching tabs, and `setExpireAfterDownload` to set the toggle when clicking the checkbox), now keep a list of old links to which something was uploaded (so that we can clear them) (why not just a variable "previousLink"? Because async events: it might fire out of order and try to clear some link twice while not clearing an old link at all), and of course changed the rest of the code to work with this and update the UI properly.

Due to all this added complexity, I feel like I probably added a new bug, especially with flaky network conditions. Do test :)

**Comment by lgommans** [comment]
> Due to all this added complexity, I feel like I probably added a new bug

Ah [yes, there we go](https://github.com/lgommans/dro.pm/commit/2878696b3d3069d77123ce5431d33ce92b5f92c1) already =P
