### ISSUE TITLE
File upload not possible anymore?

### ISSUE THREAD

**Issue by JanOonk** [lgommans/dro.pm#5]
If I recall correctly in the past it was possible to upload files and have it shortlinked. There was an file 
upload button but it is disappeared / not visible. I tried on latest FF and Chrome and Edge.
Is this on purpose? I really liked the feature.

![screenshot dro pm](https://user-images.githubusercontent.com/13236774/74658984-bbbd2900-5193-11ea-8101-22f7b2a64ae6.png)

**Comment by lgommans** [comment]
Hoi Jan! Long time no see :)

Yes, this used to be available and I just re-enabled it. The reason I temporarily disabled it is because I got word that Sophos blocks dro.pm for being malicious, and I submitted a re-evaluation request to them. I figured it would look better if the person reviewing it didn't see anything related to file sharing.

Dro.pm links expire after 12 hours anyway, so there is very little point to using this to distribute malware. The potential for abuse is very small but the poor chaps working at spyware companies (like Sophos, that sell boxes that inspect your traffic) have 3000 other potentially dangerous websites to review today, so I hoped that temporarily disabling this feature would make life easier for everyone and get the site rated similar to tinyurl or bitly (which, for some reason, are not blocked by those network spies, despite that you can have custom links that look legit but point to malware or phishing pages indefinitely -- which is a common phishing tactic, actually).

Since it's enabled again, I'll close the ticket. Thanks for raising it, I'm happy to hear the site is still useful to people! :)
